# Generated by Django 4.0.5 on 2022-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legendtype',
            name='name',
            field=models.CharField(choices=[('recon', 'Recon'), ('defensive', 'Defensive'), ('offensive', 'Offensive'), ('support', 'Support')], max_length=10),
        ),
    ]
