# Generated by Django 4.0.5 on 2022-06-24 13:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='no_image', max_length=255, verbose_name='image'),
        ),
    ]
