# Generated by Django 4.0.6 on 2022-07-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='legend_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legends.legendtype'),
        ),
    ]
