# Generated by Django 4.0.5 on 2022-06-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0004_alter_legend_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
