# Generated by Django 4.0.6 on 2022-07-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damage',
        ),
        migrations.AddField(
            model_name='weapondamage',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon'),
        ),
        migrations.AlterField(
            model_name='weaponattachment',
            name='attachment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weapons.attachment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponfiremode',
            name='firemode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weapons.firemode'),
            preserve_default=False,
        ),
    ]
