# Generated by Django 4.0.6 on 2022-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_remove_weapon_damage_weapondamage_weapon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='firemode',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
