# Generated by Django 4.0.6 on 2022-07-19 16:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_weaponattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(choices=[('Arrows', 'Arrows'), ('Energy', 'Energy'), ('Heavy', 'Heavy'), ('Light', 'Light'), ('Shotgun', 'Shotgun'), ('Sniper', 'Sniper'), ('Mythic', 'Mythic')], max_length=20, unique=True)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, default='no_image', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
