# Generated by Django 4.0.6 on 2022-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_alter_ammo_slug_alter_attachment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='name',
            field=models.CharField(choices=[('Arrows', 'Arrows'), ('Energy', 'Energy'), ('Heavy', 'Heavy'), ('Light', 'Light'), ('Shotgun', 'Shotgun'), ('Sniper', 'Sniper'), ('Mythic', 'Mythic')], max_length=20, unique=True),
        ),
    ]
