# Generated by Django 4.0.6 on 2022-07-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_ammo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponAmmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.ammo')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
    ]
