# Generated by Django 4.0.6 on 2022-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_alter_ammo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=127, unique=True),
        ),
    ]
