# Generated by Django 4.0.6 on 2022-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0006_alter_weapondamage_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(blank=True, max_length=127, unique=True),
        ),
    ]
