# Generated by Django 4.0.6 on 2022-07-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0006_modificator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
