# Generated by Django 4.0.6 on 2022-07-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0007_rangestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponMag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('modificator', models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='weapons.modificator')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
    ]
