# Generated by Django 4.0.6 on 2022-07-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0008_weaponmag'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponmag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weaponmag',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mags', to='weapons.weapon'),
        ),
    ]
