# Generated by Django 4.0.6 on 2022-07-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0008_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='ammo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weapons.ammo'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='mag_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='projectile_speed',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(max_length=50),
        ),
    ]
