# Generated by Django 4.0.6 on 2022-07-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0009_weaponmag_slug_alter_weaponmag_weapon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponmag',
            name='slug',
        ),
        migrations.AddField(
            model_name='weapon',
            name='projectile_speed',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='weapons.rangestat'),
            preserve_default=False,
        ),
    ]
