# Generated by Django 4.0.6 on 2022-07-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0010_remove_weaponmag_slug_weapon_projectile_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='projectile_speed',
        ),
    ]
