# Generated by Django 4.0.6 on 2022-07-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0010_alter_weapon_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapondamage',
            name='weapon',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='weapons.weapon'),
        ),
    ]
