# Generated by Django 4.0.6 on 2022-07-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0011_alter_weapondamage_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpm', models.FloatField(blank=True, default=None, null=True)),
                ('dps', models.FloatField(blank=True, default=None, null=True)),
                ('ttk', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='weaponfiremode',
            name='damage_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.damagestats'),
        ),
    ]
