# Generated by Django 4.0.6 on 2022-07-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0012_weapon_projectile_speed_alter_rangestat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='projectile_speed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.rangestat'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('Assault rifle', 'Assault rifle'), ('SMG', 'SMG'), ('LMG', 'LMG'), ('Marksmanweapon', 'Marksman weapon'), ('Sniper rifle', 'Sniper rifle'), ('Shotgun', 'Shotgun'), ('Pistol', 'Pistol')], max_length=50),
        ),
    ]
