# Generated by Django 4.0.6 on 2022-07-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0013_alter_weapon_projectile_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangestat',
            name='name',
            field=models.CharField(choices=[('projectile speed', 'Projectile Speed'), ('body damage', 'Body Damage'), ('head damage', 'Head Damage'), ('legs damage', 'Legs Damage')], max_length=50),
        ),
        migrations.CreateModel(
            name='WeaponDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField(blank=True, null=True)),
                ('head', models.IntegerField(blank=True, null=True)),
                ('legs', models.IntegerField(blank=True, null=True)),
                ('modificator', models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='weapons.modificator')),
                ('weapon', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='weapons.weapon')),
            ],
        ),
    ]
