# Generated by Django 4.0.6 on 2022-07-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0014_alter_rangestat_name_weapondamage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='projectile_speed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectile_speed', to='weapons.rangestat'),
        ),
        migrations.AlterField(
            model_name='weapondamage',
            name='body',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='weapons.rangestat'),
        ),
        migrations.AlterField(
            model_name='weapondamage',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='weapons.rangestat'),
        ),
        migrations.AlterField(
            model_name='weapondamage',
            name='legs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='weapons.rangestat'),
        ),
    ]
