# Generated by Django 4.0.6 on 2022-07-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0015_alter_weapon_projectile_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificator',
            name='name',
            field=models.CharField(choices=[('default', 'Default'), ('modded loader', 'Modded Loader'), ('sniper ammo amped', 'Sniper Ammo Amped'), ('double tap trigger', 'Double Tap Trigger'), ('heavy rounds revved up', 'Heavy Rounds Revved Up')], max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='projectile_speed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectile_speed', to='weapons.rangestat'),
        ),
        migrations.AlterField(
            model_name='weapondamage',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon'),
        ),
    ]
