# Generated by Django 4.0.6 on 2022-07-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0017_firemode_alter_weaponattachment_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dps', to='weapons.rangestat')),
                ('modificator', models.OneToOneField(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='weapons.modificator')),
                ('rpm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpm', to='weapons.rangestat')),
                ('ttk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttk', to='weapons.rangestat')),
            ],
        ),
    ]
