# Generated by Django 4.0.6 on 2022-07-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0018_damagestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponFireMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.damagestats')),
                ('fire_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.firemode')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapon')),
            ],
        ),
    ]
