# Generated by Django 4.0.6 on 2022-07-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0019_weaponfiremode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagestats',
            name='modificator',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='weapons.modificator'),
        ),
        migrations.AlterField(
            model_name='rangestat',
            name='name',
            field=models.CharField(choices=[('projectile speed', 'Projectile Speed'), ('body damage', 'Body Damage'), ('head damage', 'Head Damage'), ('legs damage', 'Legs Damage'), ('rpm', 'Round Per Minute'), ('dps', 'Damage Per Second'), ('ttk', 'Time To Kill')], max_length=50),
        ),
    ]
