# Generated by Django 4.0.6 on 2022-07-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0021_alter_damagestats_modificator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapondamage',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='weapons.weapon'),
        ),
        migrations.AlterField(
            model_name='weaponfiremode',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_fire_modes', to='weapons.weapon'),
        ),
        migrations.AddIndex(
            model_name='rangestat',
            index=models.Index(fields=['name'], name='weapons_ran_name_2f302e_idx'),
        ),
    ]
