# Generated by Django 4.0.5 on 2022-07-01 12:12

import abilities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(blank=True, default='no_image', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to=abilities.models.upload_to)),
                ('ability_type', models.CharField(choices=[('tactical', 'Tactical'), ('passive', 'Passive'), ('ultimate', 'Ultimate'), ('perk', 'Perk')], max_length=10)),
                ('cooldown', models.IntegerField(blank=True, null=True)),
                ('legend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legends.legend')),
            ],
        ),
    ]
