# Generated by Django 4.0.6 on 2022-07-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='legend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='legends.legend'),
        ),
    ]
