# Generated by Django 4.0.6 on 2022-07-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0002_alter_legend_legend_type'),
        ('abilities', '0002_alter_ability_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='legend',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='legends.legend'),
        ),
    ]
