# Generated by Django 4.0.5 on 2022-07-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_legend_id_ability_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.IntegerField(blank=True, help_text='Ability cooldown in seconds', null=True),
        ),
    ]
