# Generated by Django 4.0.5 on 2022-07-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
        ('abilities', '0003_alter_ability_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='legend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='legends.legend'),
        ),
    ]
