# Generated by Django 4.0.5 on 2022-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0004_alter_ability_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
